version: '3.8'

services:
  whoppah_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend

  whoppah_app:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - whoppah_db
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=whoppah.settings
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
