version: '3.8'

services:
  whoppah_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: "redis:alpine"

  whoppah_app:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - whoppah_db
      - redis
    env_file:
      - .env

volumes:
  postgres_data: